core: clk-stm32mp15: fix build error on enumarated oscillator
Fix the enum ID used with macro _CLK_PLL() that has to be updated in
the previous commit that fixed the oscillator and parent-clock enumerated
types.

Build error reported by GCC 11.0 as shown in trace below:

core/drivers/clk/clk-stm32mp15.c:362:16: error: implicit conversion from ‘enum stm32mp1_parent_id’ to ‘enum stm32mp_osc_id’ [-Werror=enum-conversion]
  362 |   .refclk[0] = (_p1),    \
      |                ^
core/drivers/clk/clk-stm32mp15.c:566:2: note: in expansion of macro ‘_CLK_PLL’
  566 |  _CLK_PLL(_PLL1, PLL_1600,
      |  ^~~~~~~~
core/drivers/clk/clk-stm32mp15.c:363:16: error: implicit conversion from ‘enum stm32mp1_parent_id’ to ‘enum stm32mp_osc_id’ [-Werror=enum-conversion]
  363 |   .refclk[1] = (_p2),    \
      |                ^
...

Change-Id: Iebad4d7bae05a10aca6ca01d5bb66c0bab2e854b
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/213926
Reviewed-by: CIBUILD <MDG-smet-aci-builds@list.st.com>
Reviewed-by: Lionel DEBIEVE <lionel.debieve@foss.st.com>
Tested-by: Lionel DEBIEVE <lionel.debieve@foss.st.com>