drivers: stm32_i2c: fix build warning
Fix build errors reported by GCC:

core/drivers/stm32_i2c.c: In function ‘get_specs’:
core/drivers/stm32_i2c.c:189:16: error: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Werror=sign-compare]
  for (i = 0; i < ARRAY_SIZE(i2c_specs); i++) {
                ^
core/drivers/stm32_i2c.c: In function ‘i2c_specs_is_consistent’:
core/drivers/stm32_i2c.c:458:16: error: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Werror=sign-compare]
  for (i = 1; i < ARRAY_SIZE(i2c_specs); i++)
                ^

Fixes: 53b17bc76baa ("i2c: stm32_i2c: allow any bus frequency")
Change-Id: Ide20e6c11e0149dfed5059f92fcdffc5e0f8b6df
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/155261
Reviewed-by: CITOOLS <smet-aci-reviews@lists.codex.cro.st.com>
Reviewed-by: Lionel DEBIEVE <lionel.debieve@st.com>