plat-stm32mp1: clk: fix build warning on unused parent clock names
Fix build error reported by GCC:

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c:535:41: error: ‘stm32mp1_clk_parent_name’ defined but not used [-Werror=unused-const-variable=]
 static const char *const __maybe_unused stm32mp1_clk_parent_name[_PARENT_NB] = {
                                         ^~~~~~~~~~~~~~~~~~~~~~~~

Fixes: 5f5cc70dfd04 ("stm32mp1: add full support for platform")
Change-Id: Ib2fa06a29ae6ca01224934a697198980bbf59b33
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/155312
Reviewed-by: CITOOLS <smet-aci-reviews@lists.codex.cro.st.com>
Reviewed-by: Lionel DEBIEVE <lionel.debieve@st.com>