plat-stm32mp1: fix build warning in pll1 settings computation functions
Fix build errors reported by GCC:

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c:1373:16: error: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Werror=sign-compare]
  for (i = 0; i < PLAT_MAX_OPP_NB; i++) {
                ^
core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c:1381:10: error: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Werror=sign-compare]
      ((i < PLAT_MAX_OPP_NB) &&
          ^
core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c:1401:9: error: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Werror=sign-compare]
  if ((i < PLAT_MAX_OPP_NB) &&
         ^

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c:1426:16: error: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Werror=sign-compare]
  for (i = 0; i < PLAT_MAX_OPP_NB; i++) {
                ^

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c:1518:16: error: comparison of integer expressions of different signedness: ‘int’ and ‘uint32_t’ {aka ‘unsigned int’} [-Werror=sign-compare]
  for (i = 0; i < count; i++) {
                ^

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c:2156:16: error: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Werror=sign-compare]
  for (i = 0; i < PLAT_MAX_OPP_NB; i++) {/
                    ^

Fixes: 0ccdf923e79f ("clk: stm32mp1: compute and manage pll1 settings")
Change-Id: I9c55164cdb2dd8311ad2651eff580ab91263cac6
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/155311
Reviewed-by: CITOOLS <smet-aci-reviews@lists.codex.cro.st.com>
Reviewed-by: Lionel DEBIEVE <lionel.debieve@st.com>