drivers: stm32_bsec: fix build warning
Fix build errors reported by GCC:

core/drivers/stm32_bsec.c:295:17: error: unused variable ‘cuint’ [-Werror=unused-variable]
  const fdt32_t *cuint;
                 ^~~~~
core/drivers/stm32_bsec.c:294:13: error: unused variable ‘len’ [-Werror=unused-variable]
  int index, len;
             ^~~
core/drivers/stm32_bsec.c:294:6: error: unused variable ‘index’ [-Werror=unused-variable]
  int index, len;
      ^~~~~
core/drivers/stm32_bsec.c:293:6: error: unused variable ‘node’ [-Werror=unused-variable]
  int node;
      ^~~~
core/drivers/stm32_bsec.c:292:8: error: unused variable ‘fdt’ [-Werror=unused-variable]
  void *fdt;
        ^~~
core/drivers/stm32_bsec.c: In function ‘bsec_read_otp’:
core/drivers/stm32_bsec.c:373:11: error: unused variable ‘exc’ [-Werror=unused-variable]
  uint32_t exc;
           ^~~

Fixes: 9a97e4365b7c ("bsec: add function to get OTP information in NVMEM layout data")
Change-Id: I7f2c3116d4b9e6fef28cb58b5ae67ac1a8c540ce
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/155262
Reviewed-by: CITOOLS <smet-aci-reviews@lists.codex.cro.st.com>
Reviewed-by: Lionel DEBIEVE <lionel.debieve@st.com>