plat-stm32mp1: fix build warning in stm32mp1_set_clksrc()
Fix build error reported by GCC:

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c:811:9: error: format ‘%x’ expects argument of type ‘unsigned int’, but argument 7 has type ‘uintptr_t’ {aka ‘long unsigned int’} [-Werror=format=]
    EMSG("CLKSRC %x start failed @ 0x%x: 0x%x\n",
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          clksrc, address, mmio_read_32(address));
                  ~~~~~~~

Fixes: 418131fe6e77 ("stm32mp1: clk: reduce clock frequency during low power mode")
Change-Id: Ie20d10242e8d3eab444e7092d1c7a6d741ebef34
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/155310
Reviewed-by: CITOOLS <smet-aci-reviews@lists.codex.cro.st.com>
Reviewed-by: Lionel DEBIEVE <lionel.debieve@st.com>