plat-stm32mp1: fix build warning in get_part_number()
Fix build error reported by GCC:

core/arch/arm/plat-stm32mp1/main.c:631:11: error: unused variable ‘otp_value’ [-Werror=unused-variable]
  uint32_t otp_value;
           ^~~~~~~~~
Fixes: 521c462a19f7 ("stm32mp1: check OPP HW support")
Change-Id: I02db4d202750ceda88dbb6027e6ed477bc5211f6
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/155309
Reviewed-by: CITOOLS <smet-aci-reviews@lists.codex.cro.st.com>
Reviewed-by: Lionel DEBIEVE <lionel.debieve@st.com>