plat-stm32mp1: clk: fix build warning gating of io compensation for pm
Fix build errors reported by GCC:

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_syscfg.c:61:7: error: too many arguments for format [-Werror=format-extra-args]
  DMSG("[0x"PRIxPTR"] SYSCFG.cmpcr = 0x"PRIx32,
       ^~~~~
lib/libutils/ext/include/trace.h:36:8: note: in definition of macro ‘trace_printf_helper’
        __VA_ARGS__)
        ^~~~~~~~~~~

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_syscfg.c:61:2: note: in expansion of macro ‘DMSG’
  DMSG("[0x"PRIxPTR"] SYSCFG.cmpcr = 0x"PRIx32,
  ^~~~

core/arch/arm/plat-stm32mp1/drivers/stm32mp1_syscfg.c: In function ‘stm32mp1_syscfg_disable_io_compensation’:
core/arch/arm/plat-stm32mp1/drivers/stm32mp1_syscfg.c:88:7: error: too many arguments for format [-Werror=format-extra-args]
  DMSG("[0x"PRIxPTR"] SYSCFG.cmpcr = 0x"PRIx32,
       ^~~~~
lib/libutils/ext/include/trace.h:36:8: note: in definition of macro ‘trace_printf_helper’
        __VA_ARGS__)
        ^~~~~~~~~~~
core/arch/arm/plat-stm32mp1/drivers/stm32mp1_syscfg.c:88:2: note: in expansion of macro ‘DMSG’
  DMSG("[0x"PRIxPTR"] SYSCFG.cmpcr = 0x"PRIx32,
  ^~~~

Fixes: b3f3564dc4dc4 ("stm32mp1: deactivate IO compensation in case of STOP mode")
Change-Id: Ia0e66b038939be985d018c75e4aff8e5e0b0b1ef
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/155313
Reviewed-by: CITOOLS <smet-aci-reviews@lists.codex.cro.st.com>
Reviewed-by: Lionel DEBIEVE <lionel.debieve@st.com>