plat-stm32mp1: pm: fix build warning for reset_other_core()
Fix build errors reported by GCC:

core/arch/arm/plat-stm32mp1/pm/low_power.c:423:13: error: ‘reset_other_core’ defined but not used [-Werror=unused-function]
 static void reset_other_core(void)
         ^~~~~~~~~~~~~~~~

Fixes: 62318247008c ("stm32mp1: independent reset: fix shutdown sequence")
Change-Id: I436053e7b3d7176f0e0c73195b43f1afe813e961
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/155314
Reviewed-by: CITOOLS <smet-aci-reviews@lists.codex.cro.st.com>
Reviewed-by: Lionel DEBIEVE <lionel.debieve@st.com>