plat-stm32mp1: fix build warning in stm32_get_iwdg_otp_config()
Fix build error reported by GCC:

core/arch/arm/plat-stm32mp1/main.c:611:58: error: suggest parentheses around comparison in operand of ‘&’ [-Werror=parentheses]
  if (otp_value & BIT(idx + HW2_OTP_IWDG_HW_ENABLE_SHIFT) != 0U) {

This change also simplifies a bit the function implementation removing
unneeded parentheses and braces.

Change-Id: I9e96788e82bc15629ecf2326519906a2a5dcf2bb
Fixes: 343a8da96cd0 ("iwdg: stm32: Fix OTP status management")
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/155308
Reviewed-by: CITOOLS <smet-aci-reviews@lists.codex.cro.st.com>
Reviewed-by: Lionel DEBIEVE <lionel.debieve@st.com>